#
###################################
# Site wide configuration
####################################
#
title: Infosec Blog By Abhi
email: abhiabhi2306@gmail.com
description: I love breaking web apps <3
#url: https://abhiabhi2306.github.io
baseurl: ""
keywords: ["blog", "jekyll"]

plugins dir: [jekyll-paginate]
paginate_path: "/page:num/"
paginate: 5
gems: [jekyll-paginate]

google_analytics: UA-144686323-1

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Warsaw
markdown:          kramdown
highlighter:       rouge


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Abhishek S
  avatar: abhi.jpg
  job: "Student/Security Researcher"
  bio: "I love breaking web apps ❤️."
  email: abhiabhi2306@gmail.com
  disqus-shortname:
  twitter: abhiabhi2306
  facebook: ab2op4u
  google:
    plus: #username
    analytics: UA-144686323-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: abhiabhi2306
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: 
  telegram: abhi900600
